In [1]:
1+1

2

In [2]:
import numpy as np

In [3]:
list=[1,2,3,4]
arr=np.array(list)


In [4]:
type(arr)


numpy.ndarray

In [5]:
arr.shape

(4,)

In [6]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [7]:
arr1=np.array([[1,2,3],[4,5,6]])

In [8]:
arr1.shape

(2, 3)

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [12]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
arr1.dtype

dtype('int64')

In [17]:
import numpy as np

array = np.arange(1, 10, 2)
print(array.shape)


(5,)


In [19]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
range(1,20,2)

range(1, 20, 2)

In [21]:
#to create array in reverse order
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [22]:

np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [24]:

#40 is elemnts 
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [25]:
#Create 3D array with 5 tables, 2 rows, 8 columns, all ones.
np.ones((5,2,8)

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [29]:
#The expression `5 + np.ones((3, 5))` adds the scalar value 5 to each element of a 2-dimensional NumPy array filled with ones.- `np.ones((3, 5))`: This creates a 2D array (matrix) with dimensions 3x5 filled with ones.- `5 + np.ones((3, 5))`: This adds 5 to each element of the 3x5 matrix created by `np.ones((3, 5))`.
#In simpler terms, it's like adding 5 to each box in a grid where all the boxes were already filled with 1.
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [31]:
print("random number generation(uniform distribution)")
np.random.rand(2,3)

random number generation(uniform distribution)


array([[0.39991358, 0.49827268, 0.44481523],
       [0.23154425, 0.66583776, 0.82533238]])

In [34]:
print("random number following a normal dstribution  with mean=0 and std=1")
np.random.rand(2,3)   

random number following a normal dstribution  with mean=0 and std=1


array([[0.45901439, 0.00099682, 0.38417136],
       [0.51366915, 0.40793339, 0.81867805]])

The code `np.random.randint(1, 100, 50)` generates an array of 50 random integers between 1 (inclusive) and 100 (exclusive) using NumPy's random module.

- `np.random`: This is the NumPy random module, which provides functions for generating random numbers.
- `randint(1, 100, 50)`: This function generates random integers. The arguments are:
  - `1`: The lower bound of the range (inclusive).
  - `100`: The upper bound of the range (exclusive).
  - `50`: The number of random integers to generate.

So, the resulting array will contain 50 random integers ranging from 1 to 99.

In [35]:
np.random.randint(1,100,50)

array([34, 64, 58, 84, 69, 74, 96, 63, 58, 98,  8, 61, 75, 76, 15, 74, 26,
       90, 24, 44, 30, 94, 79, 41, 97, 63, 76, 83, 14, 49, 29, 21, 97,  7,
       45, 44,  7, 44, 23, 11, 42, 80,  4, 26,  5, 83, 93, 92, 86,  5])

In [37]:
arr=np.arange(0,11)

In [39]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [40]:
arr[-1:7:-1]

array([10,  9,  8])

In [41]:
#universal function 

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(2,100,(3,3))

In [42]:
arr1

array([[71, 76, 61],
       [99, 53, 46],
       [73, 96,  9]])

In [43]:
arr2

array([[82, 44, 86],
       [88, 28, 17],
       [44, 76, 84]])

In [44]:
arr1+arr2

array([[153, 120, 147],
       [187,  81,  63],
       [117, 172,  93]])

In [45]:
np.exp(arr2)

array([[4.09399696e+35, 1.28516001e+19, 2.23524660e+37],
       [1.65163625e+38, 1.44625706e+12, 2.41549528e+07],
       [1.28516001e+19, 1.01480039e+33, 3.02507732e+36]])

In [46]:
np.log(arr2)

array([[4.40671925, 3.78418963, 4.4543473 ],
       [4.47733681, 3.33220451, 2.83321334],
       [3.78418963, 4.33073334, 4.4308168 ]])

In [47]:
arr1[2:]

array([[73, 96,  9]])